#!/bin/bash
NAME=$1
CONTAINER_STATUS=$(docker ps -a --filter="name=$NAME" -q | xargs) # Is the container running?  
if [ $CONTAINER_STATUS ]; then # If so...
  docker rm -f $CONTAINER_STATUS # Stop it and remove it.  
fi
if ! [ $NOTEBOOK_HOME ]; then
    NOTEBOOK_HOME=$HOME
fi
WORK_HOME=/home/jovyan/work
CMD="start-notebook.sh"
CMD_ARGS="--ip=0.0.0.0 --NotebookApp.token=\"\" --NotebookApp.disable_check_xsrf=True"
HOST_PORT=8887 # Open port on the host machine.  
if [ "$2" = "-dev" ]; then
  docker run -it --name="$NAME" \
   -v $OPENWORM_HOME/channelworm:$WORK_HOME/channelworm \
   -v $OPENWORM_HOME/celegansneuroml:$WORK_HOME/celegansneuroml \
   -p $HOST_PORT:8888 -v $NOTEBOOK_HOME:$WORK_HOME/host \
   --entrypoint=$CMD openworm/$NAME $CMD_ARGS
else
  docker run -d --name="$NAME" \
   -p $HOST_PORT:8888 -v $NOTEBOOK_HOME:$WORK_HOME/host \
   --entrypoint=$CMD openworm/$NAME $CMD_ARGS
fi

# Now access the notebook server at http://localhost:$HOST_PORT
